### ISSUE TITLE
Force close crash when debugging (example is with Cognito, but it's pretty consistent throughout)

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-unity#20]
When I install aws-unity-sdk-1.0.1-CognitoSync.unitypackage (http://aws.amazon.com/mobile/sdk/ - https://s3.amazonaws.com/aws-unity-sdk/latest/aws-unity-sdk-1.0.1.zip) from the latest update, if I connect the debugger, step through a few things (or not), and then let it continue, or disconnect, or step over the creation of a `CognitoAWSCredentials`, Unity crashes and hangs, until I eventually have to force close it.

Example of this here, https://www.youtube.com/watch?v=buAANrsEe7c and the exact project is on our github, here https://github.com/SixMinute/CognitoCrashes, nothing else installed except the unitypackage.

This particular example is with Cognito, but we're using all of Cognito, S3 and DynamoDB in our game, and this is *severely* affecting us developing our game, as we encounter many of these types of hangs since we brought in this package's code.

**Comment by seaders** [comment]
I've logged this as a Unity bug, too -> http://fogbugz.unity3d.com/default.asp?673027_b4pmi9berc8eap1g

**Comment by albertvaka** [comment]
We have been able to reproduce the crashes in OS X, even though on Windows it seems to work without a problem. Unity's Monodevelop on OS X has many bugs, and we might just be hitting one of them, but we will continue examining the problem until we find the root cause. Meanwhile, the only workaround is to attach the debugger after this point of the code.

**Comment by seaders** [comment]
Unfortunately I've put together this exact example to show what happens *continuously* to us when trying to debug, when we're nowhere near the code for creating `CognitoAWSCredentials`.  MonoDevelop was/is still quite buggy, but with this hang & crash behaviour, it's nearly unusable, especially when you run into any sort of problem.

Is there any chance you can try reach out to Unity themselves to try and find a solution?

**Comment by turacma** [comment]
When you see this problem is it when new credentials need to fetched from the service? A potential workaround if this is the case is to ensure you call RefreshAsync on the provider before making any service calls. This is certainly not the recommended workflow for a live application, but may at least allow you to more easily debug.

We will certainly see what we can do to work with Unity to address this issue's root cause.

**Comment by seaders** [comment]
This *specific* problem is *specifically* when creating a new `CognitoAWSCredentials`.  The real problem is this now happens consistently (the debugging process hangs, stops Unity from running, with the only option a Force Close) any time we debug our game, not just interacting with the Amazon library.

That, Unity hanging leading to a force close happened incredibly rarely before bringing the library in.

**Comment by seaders** [comment]
Any reason why this fix didn't make it in to 1.0.2?  Just put that into our app (so, so good that Analytics is there now as well!) but AWSSDKUtils is back to the broken way.

**Comment by albertvaka** [comment]
Hi,

The fix didn't make it into this release because there was not enough time to test it thoroughly, but it will surely be there in a next release.

Albert

**Comment by karthiksaligrama** [comment]
Hi,

This bug is resolved in the latest version of the sdk version 1.0.3.

**Comment by madangosain** [comment]
@seaders,
I still see this issue in v2.1 and v3.0
Is this issue really fixed? AWS SDK hangs the game at numerous occasions especially  when calling GetCognitoIdentity which internally try to refresh the credentials.

Does AWS unity SDK ever worked for you?  If so, which version of AWS and Unity?

Thanks
